# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NULL

gaussian_kernel <- function(x, bandwidth) {
    .Call('_KernelTest_gaussian_kernel', PACKAGE = 'KernelTest', x, bandwidth)
}

nw_smoother_point <- function(x_points, y_points, x_target, bandwidth) {
    .Call('_KernelTest_nw_smoother_point', PACKAGE = 'KernelTest', x_points, y_points, x_target, bandwidth)
}

nw_smoother <- function(x_points, y_points, x_eval, bandwidth) {
    .Call('_KernelTest_nw_smoother', PACKAGE = 'KernelTest', x_points, y_points, x_eval, bandwidth)
}

compute_hat_matrix <- function(n, bandwidth) {
    .Call('_KernelTest_compute_hat_matrix', PACKAGE = 'KernelTest', n, bandwidth)
}

compute_variance_estimates <- function(data1, data4, bandwidth, Snw) {
    .Call('_KernelTest_compute_variance_estimates', PACKAGE = 'KernelTest', data1, data4, bandwidth, Snw)
}

est_c_cpp <- function(data1, data4, max1, max4) {
    .Call('_KernelTest_est_c_cpp', PACKAGE = 'KernelTest', data1, data4, max1, max4)
}

compute_eigenvalue_stats <- function(Snw, n) {
    .Call('_KernelTest_compute_eigenvalue_stats', PACKAGE = 'KernelTest', Snw, n)
}

