// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gaussian_kernel
double gaussian_kernel(double x, double bandwidth);
RcppExport SEXP _KernelTest_gaussian_kernel(SEXP xSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian_kernel(x, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// nw_smoother_point
double nw_smoother_point(const arma::vec& x_points, const arma::vec& y_points, double x_target, double bandwidth);
RcppExport SEXP _KernelTest_nw_smoother_point(SEXP x_pointsSEXP, SEXP y_pointsSEXP, SEXP x_targetSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x_points(x_pointsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_points(y_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type x_target(x_targetSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(nw_smoother_point(x_points, y_points, x_target, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// nw_smoother
arma::vec nw_smoother(const arma::vec& x_points, const arma::vec& y_points, const arma::vec& x_eval, double bandwidth);
RcppExport SEXP _KernelTest_nw_smoother(SEXP x_pointsSEXP, SEXP y_pointsSEXP, SEXP x_evalSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x_points(x_pointsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y_points(y_pointsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(nw_smoother(x_points, y_points, x_eval, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// compute_hat_matrix
arma::mat compute_hat_matrix(int n, double bandwidth);
RcppExport SEXP _KernelTest_compute_hat_matrix(SEXP nSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hat_matrix(n, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// compute_variance_estimates
List compute_variance_estimates(const arma::mat& data1, const arma::mat& data4, double bandwidth, const arma::mat& Snw);
RcppExport SEXP _KernelTest_compute_variance_estimates(SEXP data1SEXP, SEXP data4SEXP, SEXP bandwidthSEXP, SEXP SnwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data4(data4SEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Snw(SnwSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_variance_estimates(data1, data4, bandwidth, Snw));
    return rcpp_result_gen;
END_RCPP
}
// est_c_cpp
double est_c_cpp(const arma::mat& data1, const arma::mat& data4, double max1, double max4);
RcppExport SEXP _KernelTest_est_c_cpp(SEXP data1SEXP, SEXP data4SEXP, SEXP max1SEXP, SEXP max4SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data1(data1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type data4(data4SEXP);
    Rcpp::traits::input_parameter< double >::type max1(max1SEXP);
    Rcpp::traits::input_parameter< double >::type max4(max4SEXP);
    rcpp_result_gen = Rcpp::wrap(est_c_cpp(data1, data4, max1, max4));
    return rcpp_result_gen;
END_RCPP
}
// compute_eigenvalue_stats
List compute_eigenvalue_stats(const arma::mat& Snw, int n);
RcppExport SEXP _KernelTest_compute_eigenvalue_stats(SEXP SnwSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Snw(SnwSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_eigenvalue_stats(Snw, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KernelTest_gaussian_kernel", (DL_FUNC) &_KernelTest_gaussian_kernel, 2},
    {"_KernelTest_nw_smoother_point", (DL_FUNC) &_KernelTest_nw_smoother_point, 4},
    {"_KernelTest_nw_smoother", (DL_FUNC) &_KernelTest_nw_smoother, 4},
    {"_KernelTest_compute_hat_matrix", (DL_FUNC) &_KernelTest_compute_hat_matrix, 2},
    {"_KernelTest_compute_variance_estimates", (DL_FUNC) &_KernelTest_compute_variance_estimates, 4},
    {"_KernelTest_est_c_cpp", (DL_FUNC) &_KernelTest_est_c_cpp, 4},
    {"_KernelTest_compute_eigenvalue_stats", (DL_FUNC) &_KernelTest_compute_eigenvalue_stats, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_KernelTest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
