# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gaussian kernel function
#' @param x Distance
#' @param bandwidth Bandwidth parameter
gaussian_kernel <- function(x, bandwidth) {
    .Call(`_KernelTest_gaussian_kernel`, x, bandwidth)
}

#' Nadaraya-Watson kernel smoother (single point)
#' @param x_points All x coordinates
#' @param y_points All y coordinates
#' @param x_target Target x coordinate to evaluate
#' @param bandwidth Bandwidth parameter
nw_smoother_point <- function(x_points, y_points, x_target, bandwidth) {
    .Call(`_KernelTest_nw_smoother_point`, x_points, y_points, x_target, bandwidth)
}

#' Nadaraya-Watson kernel smoother (full vector)
#' @param x_points All x coordinates
#' @param y_points All y coordinates
#' @param x_eval Evaluation points
#' @param bandwidth Bandwidth parameter
nw_smoother <- function(x_points, y_points, x_eval, bandwidth) {
    .Call(`_KernelTest_nw_smoother`, x_points, y_points, x_eval, bandwidth)
}

#' Compute the hat matrix for Nadaraya-Watson estimator
#' @param n Sample size
#' @param bandwidth Bandwidth parameter
compute_hat_matrix <- function(n, bandwidth) {
    .Call(`_KernelTest_compute_hat_matrix`, n, bandwidth)
}

#' Compute variance estimates for all genes
#' @param data1 First condition data matrix (genes x bins)
#' @param data4 Second condition data matrix (genes x bins)
#' @param bandwidth Bandwidth parameter
#' @param Snw Hat matrix
compute_variance_estimates <- function(data1, data4, bandwidth, Snw) {
    .Call(`_KernelTest_compute_variance_estimates`, data1, data4, bandwidth, Snw)
}

#' Estimate bias term (tao) from stable genes
#' @param data1 First condition data matrix
#' @param data4 Second condition data matrix
#' @param max1 Maximum threshold for condition 1
#' @param max4 Maximum threshold for condition 2
est_c_cpp <- function(data1, data4, max1, max4) {
    .Call(`_KernelTest_est_c_cpp`, data1, data4, max1, max4)
}

#' Compute eigenvalues and related statistics
#' @param Snw Hat matrix
#' @param n Sample size
compute_eigenvalue_stats <- function(Snw, n) {
    .Call(`_KernelTest_compute_eigenvalue_stats`, Snw, n)
}

